### ISSUE TITLE
PTS200 doesn't recognized as USB device after update

### ISSUE THREAD

**Issue by hurynovich** [Eddddddddy/Songguo-PTS200#21]
After I updated firmware solder is no more recognized as USB device at all and as result I cannot flash it any more.
1. I built firmware from sources v4.5.0.
2. I installed it via menu point `Update firmware` and mounted disk.
3. Solder works but it is no more flash-able and device manger doesn't see new USB device when it connected. .

What can be the problem and how to solve it?

**Comment by pricewatermouse** [comment]
You don't see "USB Serial Device (COMx)" in Windows Device Manager / Ports (COM & LPT) ?

**Comment by hurynovich** [comment]
Yes, I don't see it under Windows Device Manager too.
![image](https://github.com/Eddddddddy/Songguo-PTS200/assets/8087963/0958e40f-2046-4be7-ac63-0c42be9e254f)

Originally I did everything under Ubuntu/Linux.
And I also don't see USB/COM device with `lsusb` command or in `dmesg` logs.

I didn't installed any drivers. But I don't think it is required to detect USB device.

**Comment by pricewatermouse** [comment]
Try another PC?

I think you require some UART to send firmware

**Comment by pricewatermouse** [comment]
The ESP32-S2 chip needs to be in bootloader mode before it can be detected as a DFU device and flash. This can be achieved by pulling GPIO0 down (e.g., pressing the BOOT button), pulling RESET down for a moment, and releasing GPIO0.
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-guides/dfu.html

**GPIO0 is connected to "Confirm" button of the PTS200** 

**Flash Download Tools**
https://www.espressif.com/en/support/download/other-tools

**Comment by hurynovich** [comment]
Yeah, I also thought about this button.
But still trying to disassemble the solder somehow.

**Comment by pricewatermouse** [comment]
Just hold "Confirm" (middle) button and insert usb, then ESP32-S2 (USB\VID_303A&PID_0002&REV_0723&MI_02) device appears. After installing zadig

**Comment by pricewatermouse** [comment]
Simply press and hold the "Confirm" button (located in the middle), then insert the USB cable. This action will cause the ESP32-S2 (USB\VID_303A&PID_0002&REV_0723&MI_02) device to appear. 

Once you have installed the [Zadig tool](https://zadig.akeo.ie/) (on a Windows system), you will be able to use a USB serial device to upload firmware.

**Comment by hurynovich** [comment]
Ah, got it now.
I managed to upload firmware.
@pricewatermouse Thanks a lot!

**Comment by hurynovich** [comment]
> Simply press and hold the "Confirm" button (located in the middle), then insert the USB cable. This action will cause the ESP32-S2 (USB\VID_303A&PID_0002&REV_0723&MI_02) device to appear.
> 
> Once you have installed the [Zadig tool](https://zadig.akeo.ie/) (on a Windows system), you will be able to use a USB serial device to upload firmware.

Ah, got it now.
I managed to upload firmware.
@pricewatermouse Thanks a lot!
