### ISSUE TITLE
How to disassemble PTS200?

### ISSUE THREAD

**Issue by hurynovich** [Eddddddddy/Songguo-PTS200#22]
I am not sure if it a right place to ask.
But how to disassemble and extract circuit board from solder iron without damaging it?

I can try to pull board from but afraid to damage it.
May be do you have photos of how board is mounted inside the body?

I have such one model:
![image](https://github.com/Eddddddddy/Songguo-PTS200/assets/8087963/104b2a08-4996-4a99-81e2-6738e5e51c9e)

**Comment by pricewatermouse** [comment]
Put with buttons down, push with usb connector then pull the board with tweezer?

**Comment by hurynovich** [comment]
I didn't managed to pull it out. It feels like monolith.

Does it have some lock mechanism? 
By pressing buttons down and pushing with USB connect I didn't managed to move it at all.
And it feels like buttons doesn't block circuit board.

It also looks like cap from behind is removable.
How is it mounted? Threading, pressing, glue?
![image](https://github.com/Eddddddddy/Songguo-PTS200/assets/8087963/3b2692ce-28b7-4fe9-a689-e8931021aac1)

**Comment by pricewatermouse** [comment]
Here is a video from Eddddddddy_Wang that can provide you with some insights into board design. However, it doesn't appear to be the final version

https://www.bilibili.com/video/BV1os4y1u7qj/

**Comment by mptei** [comment]
Opening is very easy. You need to remove the display foil. To do that warm it up a little bit and then use a plectrum to take it off.
Below you find the screw which holds everything together. You need a tiny screwdriver.

**Comment by hurynovich** [comment]
Thanks, for info.
Seems like it requires 0.9 mm hex screwdriver.
