### ISSUE TITLE
Flashing problem

### ISSUE THREAD

**Issue by Kabron287** [Eddddddddy/Songguo-PTS200#6]
If I did as in instruction - nothing happened:
1. Disk appeared OK
2. Old Firmware erased OK
3. New Firmware downloaded OK
and nothing happened. Old Firmware remained.

In doc section you wrote
"If there is an upgrade failure or other problems with the firmware, you can use the factory version of the firmware and use the ESP flash tool to write the firmware at address 0x0000. Select ESP32S2-Develop-Internal USB to download."
I see no selection: **ESP32S2-Develop-Internal USB**

Maybe you describe more precise

**Comment by Eddddddddy** [comment]
There will always be a file named firmware.bin on the disk. This is normal. Try flash different versions of the firmware file to check the version number.
