### ISSUE TITLE
Where is the source code for firmware version 4.3.2

### ISSUE THREAD

**Issue by ruevs** [Eddddddddy/Songguo-PTS200#7]
Today I received a new PTS200 - and it seems like a great soldering iron!

The `Information` screen on my unit shows `VER:v4.3.2`, however I do not see such a version here - the latest is 4.3.1 and the last commit is from May 24. Does this mean that this repository will not be updated any more?

**Comment by Eddddddddy** [comment]
Sorry, there is no push for the latest code. It will be updated this Sunday.
