### ISSUE TITLE
What are these parts for?

### ISSUE THREAD

**Issue by Kabron287** [Eddddddddy/Songguo-PTS200#9]
![Details](https://github.com/Eddddddddy/Songguo-PTS200/assets/2493191/3580013b-f9df-45b2-a545-53e6ad140e65)

**Comment by temskiy** [comment]
Слева банальная подставка под паяльник.
Справа защитный колпачок (по мнению авторов...) но он одевается только на адаптер для жал T12 той стороной где нет внутренней резьбы, а вот зачем на другой стороне резьба есть загадка. И почему бы ещё не сделать возможность одевать на колпачок для родных жал тоже не ясно.

**Comment by Kabron287** [comment]
> Слева банальная подставка под паяльник.

Ну это очень сильно сказано! :))
Нужна инструкция

**Comment by temskiy** [comment]
Там есть и на картинке и в тексте описано https://mysku.club/blog/aliexpress/96385.html

**Comment by Kabron287** [comment]
Не описано как ей пользоваться, ибо не возможно в принципе

**Comment by temskiy** [comment]
¯\_(ツ)_/¯

**Comment by Kabron287** [comment]
То к темю их прижмет, то их на хвост нанижет...

**Comment by Eddddddddy** [comment]
Sorry, everyone, I really don't understand Russian at all. But I may understand what you are discussing. The long part in the picture can be used as a pen cap. It can play a protective role when storing the soldering iron. The usage is to untie a part of the front end of the soldering iron and replace it with this one.
